### ISSUE TITLE
Error while running generate.py

### ISSUE THREAD

**Issue by surajsrivathsa** [vzhong/gazp#5]
I am trying to run generate.py and train.py on sql2nl. But I am receiving the error on Colab. I am able to run training on nl2sql parser, but utterance generator seems to have a problem. Could you please let me know if this file is generated or used directly from other sources.
`FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/NL2SQL/Models/gazp/exp/sql2nl/r1/best.tar'`

**Comment by DreamerDeo** [comment]
+1

**Comment by longxudou** [comment]
Before running generate.py, you need to train nl2sql and sql2nl to get `exp/nl2sql/r1/best.tar`  and `exp/sql2nl/r1/best.tar`  respectively.
I just follow the instruction that author provided and it works now.

**Comment by longxudou** [comment]
For process_sql2nl.py, please comment out the pdb debugging part like https://github.com/DreamerDeo/gazp/blob/5f823a447ffdf5176023a01516d2be7c383294d9/preprocess_sql2nl.py#L61

**Comment by surajsrivathsa** [comment]
Thank you, its working for me now
