### ISSUE TITLE
Query Sampling

### ISSUE THREAD

**Issue by awasthiabhijeet** [vzhong/gazp#7]
Hi @vzhong 

Thanks for releasing this code.

I am looking for a method that can sample new queries from a DB (Section 2.1 of your [paper](https://arxiv.org/pdf/2009.07396.pdf))
Could you please suggest how to do that?

I guess [db2sql.py](https://github.com/vzhong/gazp/blob/main/model/db2sql.py) is what I'm looking for. But it's not being used in [generate.py](https://github.com/vzhong/gazp/blob/main/generate.py)

Thanks,

**Comment by vzhong** [comment]
Hi,

I think you are actually looking for model/ans2sql.py, which includes the sampling logic.

**Comment by awasthiabhijeet** [comment]
Thanks much! :)
